/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateProjectTemplateInput = {
  colorEndScreenMain?: boolean | null,
  colorEndScreenSub?: boolean | null,
  colorExperienceScreenHint?: boolean | null,
  colorExperienceScreenMain?: boolean | null,
  colorExperienceScreenSub?: boolean | null,
  colorFontMain?: boolean | null,
  colorFontSub?: boolean | null,
  colorFotoScreenMain?: boolean | null,
  colorFotoScreenSub?: boolean | null,
  colorLoadingScreenMain?: boolean | null,
  colorLoadingScreenSub?: boolean | null,
  colorStartScreenMain?: boolean | null,
  colorStartScreenSub?: boolean | null,
  fontLoadingHeading?: boolean | null,
  fontLoadingMain?: boolean | null,
  imageEndScreenBackground?: boolean | null,
  imageEndScreenLogo?: boolean | null,
  imageExperienceScreenAvatar?: boolean | null,
  imageExperienceScreenLogo?: boolean | null,
  imageFotoScreenScreenBackground?: boolean | null,
  imageFotoScreenScreenLogo?: boolean | null,
  imageLoadingScreenBackground?: boolean | null,
  imageLoadingScreenLogo?: boolean | null,
  imageStartScreenBackground?: boolean | null,
  imageStartScreenLogo?: boolean | null,
  linkEndScreenButtonOne?: boolean | null,
  linkEndScreenButtonThree?: boolean | null,
  linkEndScreenButtonTwo?: boolean | null,
  picture: string,
  projectExperienceLayout?: boolean | null,
  projectLink?: boolean | null,
  projectName?: boolean | null,
  projectStatus?: boolean | null,
  projectType?: boolean | null,
  projectUrl?: boolean | null,
  textEndScreenButtonOne?: boolean | null,
  textEndScreenButtonThree?: boolean | null,
  textEndScreenButtonTwo?: boolean | null,
  textEndScreenStatus?: boolean | null,
  textExperienceScreenFotoFrameStatus?: boolean | null,
  textExperienceScreenHint?: boolean | null,
  textExperienceScreenImprintContent?: boolean | null,
  textExperienceScreenImprintHeading?: boolean | null,
  textExperienceScreenInstructionsContentOne?: boolean | null,
  textExperienceScreenInstructionsContentThree?: boolean | null,
  textExperienceScreenInstructionsContentTwo?: boolean | null,
  textExperienceScreenInstructionsHeading?: boolean | null,
  textExperienceScreenLogoStatus?: boolean | null,
  textFotoScreenHint?: boolean | null,
  textFotoScreenStatus?: boolean | null,
  textLoadingScreenHint?: boolean | null,
  textLoadingScreenStatus?: boolean | null,
  textStartScreenButton?: boolean | null,
  textStartScreenHeading?: boolean | null,
  textStartScreenStatus?: boolean | null,
  textStartScreenSubheading?: boolean | null,
  title: string,
};

export type projectTemplate = {
  __typename: "projectTemplate",
  colorEndScreenMain?: boolean | null,
  colorEndScreenSub?: boolean | null,
  colorExperienceScreenHint?: boolean | null,
  colorExperienceScreenMain?: boolean | null,
  colorExperienceScreenSub?: boolean | null,
  colorFontMain?: boolean | null,
  colorFontSub?: boolean | null,
  colorFotoScreenMain?: boolean | null,
  colorFotoScreenSub?: boolean | null,
  colorLoadingScreenMain?: boolean | null,
  colorLoadingScreenSub?: boolean | null,
  colorStartScreenMain?: boolean | null,
  colorStartScreenSub?: boolean | null,
  fontLoadingHeading?: boolean | null,
  fontLoadingMain?: boolean | null,
  id: string,
  imageEndScreenBackground?: boolean | null,
  imageEndScreenLogo?: boolean | null,
  imageExperienceScreenAvatar?: boolean | null,
  imageExperienceScreenLogo?: boolean | null,
  imageFotoScreenScreenBackground?: boolean | null,
  imageFotoScreenScreenLogo?: boolean | null,
  imageLoadingScreenBackground?: boolean | null,
  imageLoadingScreenLogo?: boolean | null,
  imageStartScreenBackground?: boolean | null,
  imageStartScreenLogo?: boolean | null,
  linkEndScreenButtonOne?: boolean | null,
  linkEndScreenButtonThree?: boolean | null,
  linkEndScreenButtonTwo?: boolean | null,
  picture: string,
  projectExperienceLayout?: boolean | null,
  projectLink?: boolean | null,
  projectName?: boolean | null,
  projectStatus?: boolean | null,
  projectType?: boolean | null,
  projectUrl?: boolean | null,
  textEndScreenButtonOne?: boolean | null,
  textEndScreenButtonThree?: boolean | null,
  textEndScreenButtonTwo?: boolean | null,
  textEndScreenStatus?: boolean | null,
  textExperienceScreenFotoFrameStatus?: boolean | null,
  textExperienceScreenHint?: boolean | null,
  textExperienceScreenImprintContent?: boolean | null,
  textExperienceScreenImprintHeading?: boolean | null,
  textExperienceScreenInstructionsContentOne?: boolean | null,
  textExperienceScreenInstructionsContentThree?: boolean | null,
  textExperienceScreenInstructionsContentTwo?: boolean | null,
  textExperienceScreenInstructionsHeading?: boolean | null,
  textExperienceScreenLogoStatus?: boolean | null,
  textFotoScreenHint?: boolean | null,
  textFotoScreenStatus?: boolean | null,
  textLoadingScreenHint?: boolean | null,
  textLoadingScreenStatus?: boolean | null,
  textStartScreenButton?: boolean | null,
  textStartScreenHeading?: boolean | null,
  textStartScreenStatus?: boolean | null,
  textStartScreenSubheading?: boolean | null,
  title: string,
};

export type CreateProjectsInput = {
  colorEndScreenMain?: string | null,
  colorEndScreenSub?: string | null,
  colorExperienceScreenHint?: string | null,
  colorExperienceScreenMain?: string | null,
  colorExperienceScreenSub?: string | null,
  colorFontMain?: string | null,
  colorFontSub?: string | null,
  colorFotoScreenMain?: string | null,
  colorFotoScreenSub?: string | null,
  colorLoadingScreenMain?: string | null,
  colorLoadingScreenSub?: string | null,
  colorStartScreenMain?: string | null,
  colorStartScreenSub?: string | null,
  fontLoadingHeading?: string | null,
  fontLoadingMain?: string | null,
  imageEndScreenBackground?: string | null,
  imageEndScreenLogo?: string | null,
  imageExperienceScreenAvatar?: string | null,
  imageExperienceScreenLogo?: string | null,
  imageFotoScreenScreenBackground?: string | null,
  imageFotoScreenScreenLogo?: string | null,
  imageLoadingScreenBackground?: string | null,
  imageLoadingScreenLogo?: string | null,
  imageStartScreenBackground?: string | null,
  imageStartScreenLogo?: string | null,
  layoutActiveEndScreenStatus?: boolean | null,
  layoutActiveExperienceScreenFotoFrameStatus?: boolean | null,
  layoutActiveExperienceScreenLogoStatus?: boolean | null,
  layoutActiveFotoScreenStatus?: boolean | null,
  layoutActiveLoadingScreenStatus?: boolean | null,
  layoutActiveStartScreenStatus?: boolean | null,
  linkEndScreenButtonOne?: string | null,
  linkEndScreenButtonThree?: string | null,
  linkEndScreenButtonTwo?: string | null,
  paymentIntentId?: string | null,
  projectExperienceLayout?: string | null,
  projectLink?: string | null,
  projectName?: string | null,
  projectStatus?: string | null,
  projectType?: string | null,
  projectUrl?: string | null,
  templateId?: string | null,
  textEndScreenButtonOne?: string | null,
  textEndScreenButtonThree?: string | null,
  textEndScreenButtonTwo?: string | null,
  textEndScreenStatus?: string | null,
  textExperienceScreenFotoFrameStatus?: string | null,
  textExperienceScreenHint?: string | null,
  textExperienceScreenImprintContent?: string | null,
  textExperienceScreenImprintHeading?: string | null,
  textExperienceScreenInstructionsContentOne?: string | null,
  textExperienceScreenInstructionsContentThree?: string | null,
  textExperienceScreenInstructionsContentTwo?: string | null,
  textExperienceScreenInstructionsHeading?: string | null,
  textExperienceScreenLogoStatus?: string | null,
  textFotoScreenHint?: string | null,
  textFotoScreenStatus?: string | null,
  textLoadingScreenHint?: string | null,
  textLoadingScreenStatus?: string | null,
  textStartScreenButton?: string | null,
  textStartScreenHeading?: string | null,
  textStartScreenStatus?: string | null,
  textStartScreenSubheading?: string | null,
};

export type projects = {
  __typename: "projects",
  colorEndScreenMain?: string | null,
  colorEndScreenSub?: string | null,
  colorExperienceScreenHint?: string | null,
  colorExperienceScreenMain?: string | null,
  colorExperienceScreenSub?: string | null,
  colorFontMain?: string | null,
  colorFontSub?: string | null,
  colorFotoScreenMain?: string | null,
  colorFotoScreenSub?: string | null,
  colorLoadingScreenMain?: string | null,
  colorLoadingScreenSub?: string | null,
  colorStartScreenMain?: string | null,
  colorStartScreenSub?: string | null,
  createdAt?: number | null,
  fontLoadingHeading?: string | null,
  fontLoadingMain?: string | null,
  id: string,
  imageEndScreenBackground?: string | null,
  imageEndScreenLogo?: string | null,
  imageExperienceScreenAvatar?: string | null,
  imageExperienceScreenLogo?: string | null,
  imageFotoScreenScreenBackground?: string | null,
  imageFotoScreenScreenLogo?: string | null,
  imageLoadingScreenBackground?: string | null,
  imageLoadingScreenLogo?: string | null,
  imageStartScreenBackground?: string | null,
  imageStartScreenLogo?: string | null,
  layoutActiveEndScreenStatus?: boolean | null,
  layoutActiveExperienceScreenFotoFrameStatus?: boolean | null,
  layoutActiveExperienceScreenLogoStatus?: boolean | null,
  layoutActiveFotoScreenStatus?: boolean | null,
  layoutActiveLoadingScreenStatus?: boolean | null,
  layoutActiveStartScreenStatus?: boolean | null,
  linkEndScreenButtonOne?: string | null,
  linkEndScreenButtonThree?: string | null,
  linkEndScreenButtonTwo?: string | null,
  paymentIntentId?: string | null,
  projectExperienceLayout?: string | null,
  projectLink?: string | null,
  projectName?: string | null,
  projectStatus?: string | null,
  projectType?: string | null,
  projectUrl?: string | null,
  templateId?: string | null,
  textEndScreenButtonOne?: string | null,
  textEndScreenButtonThree?: string | null,
  textEndScreenButtonTwo?: string | null,
  textEndScreenStatus?: string | null,
  textExperienceScreenFotoFrameStatus?: string | null,
  textExperienceScreenHint?: string | null,
  textExperienceScreenImprintContent?: string | null,
  textExperienceScreenImprintHeading?: string | null,
  textExperienceScreenInstructionsContentOne?: string | null,
  textExperienceScreenInstructionsContentThree?: string | null,
  textExperienceScreenInstructionsContentTwo?: string | null,
  textExperienceScreenInstructionsHeading?: string | null,
  textExperienceScreenLogoStatus?: string | null,
  textFotoScreenHint?: string | null,
  textFotoScreenStatus?: string | null,
  textLoadingScreenHint?: string | null,
  textLoadingScreenStatus?: string | null,
  textStartScreenButton?: string | null,
  textStartScreenHeading?: string | null,
  textStartScreenStatus?: string | null,
  textStartScreenSubheading?: string | null,
  updatedAt?: number | null,
};

export type CreateUserInput = {
  available_templates?: string | null,
  email: string,
  name?: string | null,
};

export type User = {
  __typename: "User",
  available_templates?: string | null,
  email: string,
  id: string,
  name?: string | null,
};

export type DeleteProjectTemplateInput = {
  id: string,
};

export type DeleteProjectsInput = {
  id: string,
};

export type UpdateProjectTemplateInput = {
  colorEndScreenMain?: boolean | null,
  colorEndScreenSub?: boolean | null,
  colorExperienceScreenHint?: boolean | null,
  colorExperienceScreenMain?: boolean | null,
  colorExperienceScreenSub?: boolean | null,
  colorFontMain?: boolean | null,
  colorFontSub?: boolean | null,
  colorFotoScreenMain?: boolean | null,
  colorFotoScreenSub?: boolean | null,
  colorLoadingScreenMain?: boolean | null,
  colorLoadingScreenSub?: boolean | null,
  colorStartScreenMain?: boolean | null,
  colorStartScreenSub?: boolean | null,
  fontLoadingHeading?: boolean | null,
  fontLoadingMain?: boolean | null,
  id: string,
  imageEndScreenBackground?: boolean | null,
  imageEndScreenLogo?: boolean | null,
  imageExperienceScreenAvatar?: boolean | null,
  imageExperienceScreenLogo?: boolean | null,
  imageFotoScreenScreenBackground?: boolean | null,
  imageFotoScreenScreenLogo?: boolean | null,
  imageLoadingScreenBackground?: boolean | null,
  imageLoadingScreenLogo?: boolean | null,
  imageStartScreenBackground?: boolean | null,
  imageStartScreenLogo?: boolean | null,
  linkEndScreenButtonOne?: boolean | null,
  linkEndScreenButtonThree?: boolean | null,
  linkEndScreenButtonTwo?: boolean | null,
  picture?: string | null,
  projectExperienceLayout?: boolean | null,
  projectLink?: boolean | null,
  projectName?: boolean | null,
  projectStatus?: boolean | null,
  projectType?: boolean | null,
  projectUrl?: boolean | null,
  textEndScreenButtonOne?: boolean | null,
  textEndScreenButtonThree?: boolean | null,
  textEndScreenButtonTwo?: boolean | null,
  textEndScreenStatus?: boolean | null,
  textExperienceScreenFotoFrameStatus?: boolean | null,
  textExperienceScreenHint?: boolean | null,
  textExperienceScreenImprintContent?: boolean | null,
  textExperienceScreenImprintHeading?: boolean | null,
  textExperienceScreenInstructionsContentOne?: boolean | null,
  textExperienceScreenInstructionsContentThree?: boolean | null,
  textExperienceScreenInstructionsContentTwo?: boolean | null,
  textExperienceScreenInstructionsHeading?: boolean | null,
  textExperienceScreenLogoStatus?: boolean | null,
  textFotoScreenHint?: boolean | null,
  textFotoScreenStatus?: boolean | null,
  textLoadingScreenHint?: boolean | null,
  textLoadingScreenStatus?: boolean | null,
  textStartScreenButton?: boolean | null,
  textStartScreenHeading?: boolean | null,
  textStartScreenStatus?: boolean | null,
  textStartScreenSubheading?: boolean | null,
  title?: string | null,
};

export type UpdateProjectsInput = {
  colorEndScreenMain?: string | null,
  colorEndScreenSub?: string | null,
  colorExperienceScreenHint?: string | null,
  colorExperienceScreenMain?: string | null,
  colorExperienceScreenSub?: string | null,
  colorFontMain?: string | null,
  colorFontSub?: string | null,
  colorFotoScreenMain?: string | null,
  colorFotoScreenSub?: string | null,
  colorLoadingScreenMain?: string | null,
  colorLoadingScreenSub?: string | null,
  colorStartScreenMain?: string | null,
  colorStartScreenSub?: string | null,
  fontLoadingHeading?: string | null,
  fontLoadingMain?: string | null,
  id: string,
  imageEndScreenBackground?: string | null,
  imageEndScreenLogo?: string | null,
  imageExperienceScreenAvatar?: string | null,
  imageExperienceScreenLogo?: string | null,
  imageFotoScreenScreenBackground?: string | null,
  imageFotoScreenScreenLogo?: string | null,
  imageLoadingScreenBackground?: string | null,
  imageLoadingScreenLogo?: string | null,
  imageStartScreenBackground?: string | null,
  imageStartScreenLogo?: string | null,
  layoutActiveEndScreenStatus?: boolean | null,
  layoutActiveExperienceScreenFotoFrameStatus?: boolean | null,
  layoutActiveExperienceScreenLogoStatus?: boolean | null,
  layoutActiveFotoScreenStatus?: boolean | null,
  layoutActiveLoadingScreenStatus?: boolean | null,
  layoutActiveStartScreenStatus?: boolean | null,
  linkEndScreenButtonOne?: string | null,
  linkEndScreenButtonThree?: string | null,
  linkEndScreenButtonTwo?: string | null,
  paymentIntentId?: string | null,
  projectExperienceLayout?: string | null,
  projectLink?: string | null,
  projectName?: string | null,
  projectStatus?: string | null,
  projectType?: string | null,
  projectUrl?: string | null,
  templateId?: string | null,
  textEndScreenButtonOne?: string | null,
  textEndScreenButtonThree?: string | null,
  textEndScreenButtonTwo?: string | null,
  textEndScreenStatus?: string | null,
  textExperienceScreenFotoFrameStatus?: string | null,
  textExperienceScreenHint?: string | null,
  textExperienceScreenImprintContent?: string | null,
  textExperienceScreenImprintHeading?: string | null,
  textExperienceScreenInstructionsContentOne?: string | null,
  textExperienceScreenInstructionsContentThree?: string | null,
  textExperienceScreenInstructionsContentTwo?: string | null,
  textExperienceScreenInstructionsHeading?: string | null,
  textExperienceScreenLogoStatus?: string | null,
  textFotoScreenHint?: string | null,
  textFotoScreenStatus?: string | null,
  textLoadingScreenHint?: string | null,
  textLoadingScreenStatus?: string | null,
  textStartScreenButton?: string | null,
  textStartScreenHeading?: string | null,
  textStartScreenStatus?: string | null,
  textStartScreenSubheading?: string | null,
};

export type UpdateUserInput = {
  available_templates?: string | null,
  email?: string | null,
  name?: string | null,
};

export enum assetType {
  fontLoadingHeading = "fontLoadingHeading",
  fontLoadingMain = "fontLoadingMain",
  imageEndScreenBackground = "imageEndScreenBackground",
  imageEndScreenLogo = "imageEndScreenLogo",
  imageExperienceScreenAvatar = "imageExperienceScreenAvatar",
  imageExperienceScreenLogo = "imageExperienceScreenLogo",
  imageFotoScreenScreenBackground = "imageFotoScreenScreenBackground",
  imageFotoScreenScreenLogo = "imageFotoScreenScreenLogo",
  imageLoadingScreenBackground = "imageLoadingScreenBackground",
  imageLoadingScreenLogo = "imageLoadingScreenLogo",
  imageStartScreenBackground = "imageStartScreenBackground",
  imageStartScreenLogo = "imageStartScreenLogo",
}


export enum fileType {
  jpg = "jpg",
  otf = "otf",
  png = "png",
  ttf = "ttf",
}


export type TableProjectTemplateFilterInput = {
  colorEndScreenMain?: TableBooleanFilterInput | null,
  colorEndScreenSub?: TableBooleanFilterInput | null,
  colorExperienceScreenHint?: TableBooleanFilterInput | null,
  colorExperienceScreenMain?: TableBooleanFilterInput | null,
  colorExperienceScreenSub?: TableBooleanFilterInput | null,
  colorFontMain?: TableBooleanFilterInput | null,
  colorFontSub?: TableBooleanFilterInput | null,
  colorFotoScreenMain?: TableBooleanFilterInput | null,
  colorFotoScreenSub?: TableBooleanFilterInput | null,
  colorLoadingScreenMain?: TableBooleanFilterInput | null,
  colorLoadingScreenSub?: TableBooleanFilterInput | null,
  colorStartScreenMain?: TableBooleanFilterInput | null,
  colorStartScreenSub?: TableBooleanFilterInput | null,
  fontLoadingHeading?: TableBooleanFilterInput | null,
  fontLoadingMain?: TableBooleanFilterInput | null,
  id?: TableIDFilterInput | null,
  imageEndScreenBackground?: TableBooleanFilterInput | null,
  imageEndScreenLogo?: TableBooleanFilterInput | null,
  imageExperienceScreenAvatar?: TableBooleanFilterInput | null,
  imageExperienceScreenLogo?: TableBooleanFilterInput | null,
  imageFotoScreenScreenBackground?: TableBooleanFilterInput | null,
  imageFotoScreenScreenLogo?: TableBooleanFilterInput | null,
  imageLoadingScreenBackground?: TableBooleanFilterInput | null,
  imageLoadingScreenLogo?: TableBooleanFilterInput | null,
  imageStartScreenBackground?: TableBooleanFilterInput | null,
  imageStartScreenLogo?: TableBooleanFilterInput | null,
  linkEndScreenButtonOne?: TableBooleanFilterInput | null,
  linkEndScreenButtonThree?: TableBooleanFilterInput | null,
  linkEndScreenButtonTwo?: TableBooleanFilterInput | null,
  picture?: TableStringFilterInput | null,
  projectExperienceLayout?: TableBooleanFilterInput | null,
  projectLink?: TableBooleanFilterInput | null,
  projectName?: TableBooleanFilterInput | null,
  projectStatus?: TableBooleanFilterInput | null,
  projectType?: TableBooleanFilterInput | null,
  projectUrl?: TableBooleanFilterInput | null,
  textEndScreenButtonOne?: TableBooleanFilterInput | null,
  textEndScreenButtonThree?: TableBooleanFilterInput | null,
  textEndScreenButtonTwo?: TableBooleanFilterInput | null,
  textEndScreenStatus?: TableBooleanFilterInput | null,
  textExperienceScreenFotoFrameStatus?: TableBooleanFilterInput | null,
  textExperienceScreenHint?: TableBooleanFilterInput | null,
  textExperienceScreenImprintContent?: TableBooleanFilterInput | null,
  textExperienceScreenImprintHeading?: TableBooleanFilterInput | null,
  textExperienceScreenInstructionsContentOne?: TableBooleanFilterInput | null,
  textExperienceScreenInstructionsContentThree?: TableBooleanFilterInput | null,
  textExperienceScreenInstructionsContentTwo?: TableBooleanFilterInput | null,
  textExperienceScreenInstructionsHeading?: TableBooleanFilterInput | null,
  textExperienceScreenLogoStatus?: TableBooleanFilterInput | null,
  textFotoScreenHint?: TableBooleanFilterInput | null,
  textFotoScreenStatus?: TableBooleanFilterInput | null,
  textLoadingScreenHint?: TableBooleanFilterInput | null,
  textLoadingScreenStatus?: TableBooleanFilterInput | null,
  textStartScreenButton?: TableBooleanFilterInput | null,
  textStartScreenHeading?: TableBooleanFilterInput | null,
  textStartScreenStatus?: TableBooleanFilterInput | null,
  textStartScreenSubheading?: TableBooleanFilterInput | null,
  title?: TableStringFilterInput | null,
};

export type TableBooleanFilterInput = {
  eq?: boolean | null,
  ne?: boolean | null,
};

export type TableIDFilterInput = {
  beginsWith?: string | null,
  between?: Array< string | null > | null,
  contains?: string | null,
  eq?: string | null,
  ge?: string | null,
  gt?: string | null,
  le?: string | null,
  lt?: string | null,
  ne?: string | null,
  notContains?: string | null,
};

export type TableStringFilterInput = {
  beginsWith?: string | null,
  between?: Array< string | null > | null,
  contains?: string | null,
  eq?: string | null,
  ge?: string | null,
  gt?: string | null,
  le?: string | null,
  lt?: string | null,
  ne?: string | null,
  notContains?: string | null,
};

export type projectTemplateConnection = {
  __typename: "projectTemplateConnection",
  items?:  Array<projectTemplate | null > | null,
  nextToken?: string | null,
};

export type TableProjectsFilterInput = {
  colorExperienceHint?: TableStringFilterInput | null,
  colorExperienceMain?: TableStringFilterInput | null,
  colorExperienceSub?: TableStringFilterInput | null,
  colorLoadingSub?: TableStringFilterInput | null,
  colorMain?: TableStringFilterInput | null,
  fontLoadingHeading?: TableStringFilterInput | null,
  fontLoadingMain?: TableStringFilterInput | null,
  id?: TableIDFilterInput | null,
  imageAvatar?: TableStringFilterInput | null,
  imageEndScreen?: TableStringFilterInput | null,
  imageExperienceScreen?: TableStringFilterInput | null,
  imageFotoScreen?: TableStringFilterInput | null,
  imageLoadingScreen?: TableStringFilterInput | null,
  imageStartScreen?: TableStringFilterInput | null,
  projectExperienceLayout?: TableStringFilterInput | null,
  projectLink?: TableStringFilterInput | null,
  projectName?: TableStringFilterInput | null,
  projectStatus?: TableStringFilterInput | null,
  projectType?: TableStringFilterInput | null,
  projectUrl?: TableStringFilterInput | null,
  textExperienceHint?: TableStringFilterInput | null,
  textExperienceImprint?: TableStringFilterInput | null,
  textExperienceInstructions?: TableStringFilterInput | null,
  textLoadingScreenHint?: TableStringFilterInput | null,
  textStartScreenHeading?: TableStringFilterInput | null,
  textStartScreenSubheading?: TableStringFilterInput | null,
  userId?: TableStringFilterInput | null,
};

export type projectsConnection = {
  __typename: "projectsConnection",
  items?:  Array<projects | null > | null,
  nextToken?: string | null,
};

export type CreateProjectTemplateMutationVariables = {
  input: CreateProjectTemplateInput,
};

export type CreateProjectTemplateMutation = {
  createProjectTemplate?:  {
    __typename: "projectTemplate",
    colorEndScreenMain?: boolean | null,
    colorEndScreenSub?: boolean | null,
    colorExperienceScreenHint?: boolean | null,
    colorExperienceScreenMain?: boolean | null,
    colorExperienceScreenSub?: boolean | null,
    colorFontMain?: boolean | null,
    colorFontSub?: boolean | null,
    colorFotoScreenMain?: boolean | null,
    colorFotoScreenSub?: boolean | null,
    colorLoadingScreenMain?: boolean | null,
    colorLoadingScreenSub?: boolean | null,
    colorStartScreenMain?: boolean | null,
    colorStartScreenSub?: boolean | null,
    fontLoadingHeading?: boolean | null,
    fontLoadingMain?: boolean | null,
    id: string,
    imageEndScreenBackground?: boolean | null,
    imageEndScreenLogo?: boolean | null,
    imageExperienceScreenAvatar?: boolean | null,
    imageExperienceScreenLogo?: boolean | null,
    imageFotoScreenScreenBackground?: boolean | null,
    imageFotoScreenScreenLogo?: boolean | null,
    imageLoadingScreenBackground?: boolean | null,
    imageLoadingScreenLogo?: boolean | null,
    imageStartScreenBackground?: boolean | null,
    imageStartScreenLogo?: boolean | null,
    linkEndScreenButtonOne?: boolean | null,
    linkEndScreenButtonThree?: boolean | null,
    linkEndScreenButtonTwo?: boolean | null,
    picture: string,
    projectExperienceLayout?: boolean | null,
    projectLink?: boolean | null,
    projectName?: boolean | null,
    projectStatus?: boolean | null,
    projectType?: boolean | null,
    projectUrl?: boolean | null,
    textEndScreenButtonOne?: boolean | null,
    textEndScreenButtonThree?: boolean | null,
    textEndScreenButtonTwo?: boolean | null,
    textEndScreenStatus?: boolean | null,
    textExperienceScreenFotoFrameStatus?: boolean | null,
    textExperienceScreenHint?: boolean | null,
    textExperienceScreenImprintContent?: boolean | null,
    textExperienceScreenImprintHeading?: boolean | null,
    textExperienceScreenInstructionsContentOne?: boolean | null,
    textExperienceScreenInstructionsContentThree?: boolean | null,
    textExperienceScreenInstructionsContentTwo?: boolean | null,
    textExperienceScreenInstructionsHeading?: boolean | null,
    textExperienceScreenLogoStatus?: boolean | null,
    textFotoScreenHint?: boolean | null,
    textFotoScreenStatus?: boolean | null,
    textLoadingScreenHint?: boolean | null,
    textLoadingScreenStatus?: boolean | null,
    textStartScreenButton?: boolean | null,
    textStartScreenHeading?: boolean | null,
    textStartScreenStatus?: boolean | null,
    textStartScreenSubheading?: boolean | null,
    title: string,
  } | null,
};

export type CreateProjectsMutationVariables = {
  input: CreateProjectsInput,
};

export type CreateProjectsMutation = {
  createProjects?:  {
    __typename: "projects",
    colorEndScreenMain?: string | null,
    colorEndScreenSub?: string | null,
    colorExperienceScreenHint?: string | null,
    colorExperienceScreenMain?: string | null,
    colorExperienceScreenSub?: string | null,
    colorFontMain?: string | null,
    colorFontSub?: string | null,
    colorFotoScreenMain?: string | null,
    colorFotoScreenSub?: string | null,
    colorLoadingScreenMain?: string | null,
    colorLoadingScreenSub?: string | null,
    colorStartScreenMain?: string | null,
    colorStartScreenSub?: string | null,
    createdAt?: number | null,
    fontLoadingHeading?: string | null,
    fontLoadingMain?: string | null,
    id: string,
    imageEndScreenBackground?: string | null,
    imageEndScreenLogo?: string | null,
    imageExperienceScreenAvatar?: string | null,
    imageExperienceScreenLogo?: string | null,
    imageFotoScreenScreenBackground?: string | null,
    imageFotoScreenScreenLogo?: string | null,
    imageLoadingScreenBackground?: string | null,
    imageLoadingScreenLogo?: string | null,
    imageStartScreenBackground?: string | null,
    imageStartScreenLogo?: string | null,
    layoutActiveEndScreenStatus?: boolean | null,
    layoutActiveExperienceScreenFotoFrameStatus?: boolean | null,
    layoutActiveExperienceScreenLogoStatus?: boolean | null,
    layoutActiveFotoScreenStatus?: boolean | null,
    layoutActiveLoadingScreenStatus?: boolean | null,
    layoutActiveStartScreenStatus?: boolean | null,
    linkEndScreenButtonOne?: string | null,
    linkEndScreenButtonThree?: string | null,
    linkEndScreenButtonTwo?: string | null,
    paymentIntentId?: string | null,
    projectExperienceLayout?: string | null,
    projectLink?: string | null,
    projectName?: string | null,
    projectStatus?: string | null,
    projectType?: string | null,
    projectUrl?: string | null,
    templateId?: string | null,
    textEndScreenButtonOne?: string | null,
    textEndScreenButtonThree?: string | null,
    textEndScreenButtonTwo?: string | null,
    textEndScreenStatus?: string | null,
    textExperienceScreenFotoFrameStatus?: string | null,
    textExperienceScreenHint?: string | null,
    textExperienceScreenImprintContent?: string | null,
    textExperienceScreenImprintHeading?: string | null,
    textExperienceScreenInstructionsContentOne?: string | null,
    textExperienceScreenInstructionsContentThree?: string | null,
    textExperienceScreenInstructionsContentTwo?: string | null,
    textExperienceScreenInstructionsHeading?: string | null,
    textExperienceScreenLogoStatus?: string | null,
    textFotoScreenHint?: string | null,
    textFotoScreenStatus?: string | null,
    textLoadingScreenHint?: string | null,
    textLoadingScreenStatus?: string | null,
    textStartScreenButton?: string | null,
    textStartScreenHeading?: string | null,
    textStartScreenStatus?: string | null,
    textStartScreenSubheading?: string | null,
    updatedAt?: number | null,
  } | null,
};

export type CreateUserMutationVariables = {
  input: CreateUserInput,
};

export type CreateUserMutation = {
  createUser?:  {
    __typename: "User",
    available_templates?: string | null,
    email: string,
    id: string,
    name?: string | null,
  } | null,
};

export type DeleteProjectTemplateMutationVariables = {
  input: DeleteProjectTemplateInput,
};

export type DeleteProjectTemplateMutation = {
  deleteProjectTemplate?:  {
    __typename: "projectTemplate",
    colorEndScreenMain?: boolean | null,
    colorEndScreenSub?: boolean | null,
    colorExperienceScreenHint?: boolean | null,
    colorExperienceScreenMain?: boolean | null,
    colorExperienceScreenSub?: boolean | null,
    colorFontMain?: boolean | null,
    colorFontSub?: boolean | null,
    colorFotoScreenMain?: boolean | null,
    colorFotoScreenSub?: boolean | null,
    colorLoadingScreenMain?: boolean | null,
    colorLoadingScreenSub?: boolean | null,
    colorStartScreenMain?: boolean | null,
    colorStartScreenSub?: boolean | null,
    fontLoadingHeading?: boolean | null,
    fontLoadingMain?: boolean | null,
    id: string,
    imageEndScreenBackground?: boolean | null,
    imageEndScreenLogo?: boolean | null,
    imageExperienceScreenAvatar?: boolean | null,
    imageExperienceScreenLogo?: boolean | null,
    imageFotoScreenScreenBackground?: boolean | null,
    imageFotoScreenScreenLogo?: boolean | null,
    imageLoadingScreenBackground?: boolean | null,
    imageLoadingScreenLogo?: boolean | null,
    imageStartScreenBackground?: boolean | null,
    imageStartScreenLogo?: boolean | null,
    linkEndScreenButtonOne?: boolean | null,
    linkEndScreenButtonThree?: boolean | null,
    linkEndScreenButtonTwo?: boolean | null,
    picture: string,
    projectExperienceLayout?: boolean | null,
    projectLink?: boolean | null,
    projectName?: boolean | null,
    projectStatus?: boolean | null,
    projectType?: boolean | null,
    projectUrl?: boolean | null,
    textEndScreenButtonOne?: boolean | null,
    textEndScreenButtonThree?: boolean | null,
    textEndScreenButtonTwo?: boolean | null,
    textEndScreenStatus?: boolean | null,
    textExperienceScreenFotoFrameStatus?: boolean | null,
    textExperienceScreenHint?: boolean | null,
    textExperienceScreenImprintContent?: boolean | null,
    textExperienceScreenImprintHeading?: boolean | null,
    textExperienceScreenInstructionsContentOne?: boolean | null,
    textExperienceScreenInstructionsContentThree?: boolean | null,
    textExperienceScreenInstructionsContentTwo?: boolean | null,
    textExperienceScreenInstructionsHeading?: boolean | null,
    textExperienceScreenLogoStatus?: boolean | null,
    textFotoScreenHint?: boolean | null,
    textFotoScreenStatus?: boolean | null,
    textLoadingScreenHint?: boolean | null,
    textLoadingScreenStatus?: boolean | null,
    textStartScreenButton?: boolean | null,
    textStartScreenHeading?: boolean | null,
    textStartScreenStatus?: boolean | null,
    textStartScreenSubheading?: boolean | null,
    title: string,
  } | null,
};

export type DeleteProjectsMutationVariables = {
  input: DeleteProjectsInput,
};

export type DeleteProjectsMutation = {
  deleteProjects?:  {
    __typename: "projects",
    colorEndScreenMain?: string | null,
    colorEndScreenSub?: string | null,
    colorExperienceScreenHint?: string | null,
    colorExperienceScreenMain?: string | null,
    colorExperienceScreenSub?: string | null,
    colorFontMain?: string | null,
    colorFontSub?: string | null,
    colorFotoScreenMain?: string | null,
    colorFotoScreenSub?: string | null,
    colorLoadingScreenMain?: string | null,
    colorLoadingScreenSub?: string | null,
    colorStartScreenMain?: string | null,
    colorStartScreenSub?: string | null,
    createdAt?: number | null,
    fontLoadingHeading?: string | null,
    fontLoadingMain?: string | null,
    id: string,
    imageEndScreenBackground?: string | null,
    imageEndScreenLogo?: string | null,
    imageExperienceScreenAvatar?: string | null,
    imageExperienceScreenLogo?: string | null,
    imageFotoScreenScreenBackground?: string | null,
    imageFotoScreenScreenLogo?: string | null,
    imageLoadingScreenBackground?: string | null,
    imageLoadingScreenLogo?: string | null,
    imageStartScreenBackground?: string | null,
    imageStartScreenLogo?: string | null,
    layoutActiveEndScreenStatus?: boolean | null,
    layoutActiveExperienceScreenFotoFrameStatus?: boolean | null,
    layoutActiveExperienceScreenLogoStatus?: boolean | null,
    layoutActiveFotoScreenStatus?: boolean | null,
    layoutActiveLoadingScreenStatus?: boolean | null,
    layoutActiveStartScreenStatus?: boolean | null,
    linkEndScreenButtonOne?: string | null,
    linkEndScreenButtonThree?: string | null,
    linkEndScreenButtonTwo?: string | null,
    paymentIntentId?: string | null,
    projectExperienceLayout?: string | null,
    projectLink?: string | null,
    projectName?: string | null,
    projectStatus?: string | null,
    projectType?: string | null,
    projectUrl?: string | null,
    templateId?: string | null,
    textEndScreenButtonOne?: string | null,
    textEndScreenButtonThree?: string | null,
    textEndScreenButtonTwo?: string | null,
    textEndScreenStatus?: string | null,
    textExperienceScreenFotoFrameStatus?: string | null,
    textExperienceScreenHint?: string | null,
    textExperienceScreenImprintContent?: string | null,
    textExperienceScreenImprintHeading?: string | null,
    textExperienceScreenInstructionsContentOne?: string | null,
    textExperienceScreenInstructionsContentThree?: string | null,
    textExperienceScreenInstructionsContentTwo?: string | null,
    textExperienceScreenInstructionsHeading?: string | null,
    textExperienceScreenLogoStatus?: string | null,
    textFotoScreenHint?: string | null,
    textFotoScreenStatus?: string | null,
    textLoadingScreenHint?: string | null,
    textLoadingScreenStatus?: string | null,
    textStartScreenButton?: string | null,
    textStartScreenHeading?: string | null,
    textStartScreenStatus?: string | null,
    textStartScreenSubheading?: string | null,
    updatedAt?: number | null,
  } | null,
};

export type UpdateProjectTemplateMutationVariables = {
  input: UpdateProjectTemplateInput,
};

export type UpdateProjectTemplateMutation = {
  updateProjectTemplate?:  {
    __typename: "projectTemplate",
    colorEndScreenMain?: boolean | null,
    colorEndScreenSub?: boolean | null,
    colorExperienceScreenHint?: boolean | null,
    colorExperienceScreenMain?: boolean | null,
    colorExperienceScreenSub?: boolean | null,
    colorFontMain?: boolean | null,
    colorFontSub?: boolean | null,
    colorFotoScreenMain?: boolean | null,
    colorFotoScreenSub?: boolean | null,
    colorLoadingScreenMain?: boolean | null,
    colorLoadingScreenSub?: boolean | null,
    colorStartScreenMain?: boolean | null,
    colorStartScreenSub?: boolean | null,
    fontLoadingHeading?: boolean | null,
    fontLoadingMain?: boolean | null,
    id: string,
    imageEndScreenBackground?: boolean | null,
    imageEndScreenLogo?: boolean | null,
    imageExperienceScreenAvatar?: boolean | null,
    imageExperienceScreenLogo?: boolean | null,
    imageFotoScreenScreenBackground?: boolean | null,
    imageFotoScreenScreenLogo?: boolean | null,
    imageLoadingScreenBackground?: boolean | null,
    imageLoadingScreenLogo?: boolean | null,
    imageStartScreenBackground?: boolean | null,
    imageStartScreenLogo?: boolean | null,
    linkEndScreenButtonOne?: boolean | null,
    linkEndScreenButtonThree?: boolean | null,
    linkEndScreenButtonTwo?: boolean | null,
    picture: string,
    projectExperienceLayout?: boolean | null,
    projectLink?: boolean | null,
    projectName?: boolean | null,
    projectStatus?: boolean | null,
    projectType?: boolean | null,
    projectUrl?: boolean | null,
    textEndScreenButtonOne?: boolean | null,
    textEndScreenButtonThree?: boolean | null,
    textEndScreenButtonTwo?: boolean | null,
    textEndScreenStatus?: boolean | null,
    textExperienceScreenFotoFrameStatus?: boolean | null,
    textExperienceScreenHint?: boolean | null,
    textExperienceScreenImprintContent?: boolean | null,
    textExperienceScreenImprintHeading?: boolean | null,
    textExperienceScreenInstructionsContentOne?: boolean | null,
    textExperienceScreenInstructionsContentThree?: boolean | null,
    textExperienceScreenInstructionsContentTwo?: boolean | null,
    textExperienceScreenInstructionsHeading?: boolean | null,
    textExperienceScreenLogoStatus?: boolean | null,
    textFotoScreenHint?: boolean | null,
    textFotoScreenStatus?: boolean | null,
    textLoadingScreenHint?: boolean | null,
    textLoadingScreenStatus?: boolean | null,
    textStartScreenButton?: boolean | null,
    textStartScreenHeading?: boolean | null,
    textStartScreenStatus?: boolean | null,
    textStartScreenSubheading?: boolean | null,
    title: string,
  } | null,
};

export type UpdateProjectsMutationVariables = {
  input: UpdateProjectsInput,
};

export type UpdateProjectsMutation = {
  updateProjects?:  {
    __typename: "projects",
    colorEndScreenMain?: string | null,
    colorEndScreenSub?: string | null,
    colorExperienceScreenHint?: string | null,
    colorExperienceScreenMain?: string | null,
    colorExperienceScreenSub?: string | null,
    colorFontMain?: string | null,
    colorFontSub?: string | null,
    colorFotoScreenMain?: string | null,
    colorFotoScreenSub?: string | null,
    colorLoadingScreenMain?: string | null,
    colorLoadingScreenSub?: string | null,
    colorStartScreenMain?: string | null,
    colorStartScreenSub?: string | null,
    createdAt?: number | null,
    fontLoadingHeading?: string | null,
    fontLoadingMain?: string | null,
    id: string,
    imageEndScreenBackground?: string | null,
    imageEndScreenLogo?: string | null,
    imageExperienceScreenAvatar?: string | null,
    imageExperienceScreenLogo?: string | null,
    imageFotoScreenScreenBackground?: string | null,
    imageFotoScreenScreenLogo?: string | null,
    imageLoadingScreenBackground?: string | null,
    imageLoadingScreenLogo?: string | null,
    imageStartScreenBackground?: string | null,
    imageStartScreenLogo?: string | null,
    layoutActiveEndScreenStatus?: boolean | null,
    layoutActiveExperienceScreenFotoFrameStatus?: boolean | null,
    layoutActiveExperienceScreenLogoStatus?: boolean | null,
    layoutActiveFotoScreenStatus?: boolean | null,
    layoutActiveLoadingScreenStatus?: boolean | null,
    layoutActiveStartScreenStatus?: boolean | null,
    linkEndScreenButtonOne?: string | null,
    linkEndScreenButtonThree?: string | null,
    linkEndScreenButtonTwo?: string | null,
    paymentIntentId?: string | null,
    projectExperienceLayout?: string | null,
    projectLink?: string | null,
    projectName?: string | null,
    projectStatus?: string | null,
    projectType?: string | null,
    projectUrl?: string | null,
    templateId?: string | null,
    textEndScreenButtonOne?: string | null,
    textEndScreenButtonThree?: string | null,
    textEndScreenButtonTwo?: string | null,
    textEndScreenStatus?: string | null,
    textExperienceScreenFotoFrameStatus?: string | null,
    textExperienceScreenHint?: string | null,
    textExperienceScreenImprintContent?: string | null,
    textExperienceScreenImprintHeading?: string | null,
    textExperienceScreenInstructionsContentOne?: string | null,
    textExperienceScreenInstructionsContentThree?: string | null,
    textExperienceScreenInstructionsContentTwo?: string | null,
    textExperienceScreenInstructionsHeading?: string | null,
    textExperienceScreenLogoStatus?: string | null,
    textFotoScreenHint?: string | null,
    textFotoScreenStatus?: string | null,
    textLoadingScreenHint?: string | null,
    textLoadingScreenStatus?: string | null,
    textStartScreenButton?: string | null,
    textStartScreenHeading?: string | null,
    textStartScreenStatus?: string | null,
    textStartScreenSubheading?: string | null,
    updatedAt?: number | null,
  } | null,
};

export type UpdateUserMutationVariables = {
  input: UpdateUserInput,
};

export type UpdateUserMutation = {
  updateUser?:  {
    __typename: "User",
    available_templates?: string | null,
    email: string,
    id: string,
    name?: string | null,
  } | null,
};

export type GetIdentityQuery = {
  getIdentity?: string | null,
};

export type GetProjectQueryVariables = {
  id: string,
  uid: string,
};

export type GetProjectQuery = {
  getProject?:  {
    __typename: "projects",
    colorEndScreenMain?: string | null,
    colorEndScreenSub?: string | null,
    colorExperienceScreenHint?: string | null,
    colorExperienceScreenMain?: string | null,
    colorExperienceScreenSub?: string | null,
    colorFontMain?: string | null,
    colorFontSub?: string | null,
    colorFotoScreenMain?: string | null,
    colorFotoScreenSub?: string | null,
    colorLoadingScreenMain?: string | null,
    colorLoadingScreenSub?: string | null,
    colorStartScreenMain?: string | null,
    colorStartScreenSub?: string | null,
    createdAt?: number | null,
    fontLoadingHeading?: string | null,
    fontLoadingMain?: string | null,
    id: string,
    imageEndScreenBackground?: string | null,
    imageEndScreenLogo?: string | null,
    imageExperienceScreenAvatar?: string | null,
    imageExperienceScreenLogo?: string | null,
    imageFotoScreenScreenBackground?: string | null,
    imageFotoScreenScreenLogo?: string | null,
    imageLoadingScreenBackground?: string | null,
    imageLoadingScreenLogo?: string | null,
    imageStartScreenBackground?: string | null,
    imageStartScreenLogo?: string | null,
    layoutActiveEndScreenStatus?: boolean | null,
    layoutActiveExperienceScreenFotoFrameStatus?: boolean | null,
    layoutActiveExperienceScreenLogoStatus?: boolean | null,
    layoutActiveFotoScreenStatus?: boolean | null,
    layoutActiveLoadingScreenStatus?: boolean | null,
    layoutActiveStartScreenStatus?: boolean | null,
    linkEndScreenButtonOne?: string | null,
    linkEndScreenButtonThree?: string | null,
    linkEndScreenButtonTwo?: string | null,
    paymentIntentId?: string | null,
    projectExperienceLayout?: string | null,
    projectLink?: string | null,
    projectName?: string | null,
    projectStatus?: string | null,
    projectType?: string | null,
    projectUrl?: string | null,
    templateId?: string | null,
    textEndScreenButtonOne?: string | null,
    textEndScreenButtonThree?: string | null,
    textEndScreenButtonTwo?: string | null,
    textEndScreenStatus?: string | null,
    textExperienceScreenFotoFrameStatus?: string | null,
    textExperienceScreenHint?: string | null,
    textExperienceScreenImprintContent?: string | null,
    textExperienceScreenImprintHeading?: string | null,
    textExperienceScreenInstructionsContentOne?: string | null,
    textExperienceScreenInstructionsContentThree?: string | null,
    textExperienceScreenInstructionsContentTwo?: string | null,
    textExperienceScreenInstructionsHeading?: string | null,
    textExperienceScreenLogoStatus?: string | null,
    textFotoScreenHint?: string | null,
    textFotoScreenStatus?: string | null,
    textLoadingScreenHint?: string | null,
    textLoadingScreenStatus?: string | null,
    textStartScreenButton?: string | null,
    textStartScreenHeading?: string | null,
    textStartScreenStatus?: string | null,
    textStartScreenSubheading?: string | null,
    updatedAt?: number | null,
  } | null,
};

export type GetProjectTemplateQueryVariables = {
  id: string,
};

export type GetProjectTemplateQuery = {
  getProjectTemplate?:  {
    __typename: "projectTemplate",
    colorEndScreenMain?: boolean | null,
    colorEndScreenSub?: boolean | null,
    colorExperienceScreenHint?: boolean | null,
    colorExperienceScreenMain?: boolean | null,
    colorExperienceScreenSub?: boolean | null,
    colorFontMain?: boolean | null,
    colorFontSub?: boolean | null,
    colorFotoScreenMain?: boolean | null,
    colorFotoScreenSub?: boolean | null,
    colorLoadingScreenMain?: boolean | null,
    colorLoadingScreenSub?: boolean | null,
    colorStartScreenMain?: boolean | null,
    colorStartScreenSub?: boolean | null,
    fontLoadingHeading?: boolean | null,
    fontLoadingMain?: boolean | null,
    id: string,
    imageEndScreenBackground?: boolean | null,
    imageEndScreenLogo?: boolean | null,
    imageExperienceScreenAvatar?: boolean | null,
    imageExperienceScreenLogo?: boolean | null,
    imageFotoScreenScreenBackground?: boolean | null,
    imageFotoScreenScreenLogo?: boolean | null,
    imageLoadingScreenBackground?: boolean | null,
    imageLoadingScreenLogo?: boolean | null,
    imageStartScreenBackground?: boolean | null,
    imageStartScreenLogo?: boolean | null,
    linkEndScreenButtonOne?: boolean | null,
    linkEndScreenButtonThree?: boolean | null,
    linkEndScreenButtonTwo?: boolean | null,
    picture: string,
    projectExperienceLayout?: boolean | null,
    projectLink?: boolean | null,
    projectName?: boolean | null,
    projectStatus?: boolean | null,
    projectType?: boolean | null,
    projectUrl?: boolean | null,
    textEndScreenButtonOne?: boolean | null,
    textEndScreenButtonThree?: boolean | null,
    textEndScreenButtonTwo?: boolean | null,
    textEndScreenStatus?: boolean | null,
    textExperienceScreenFotoFrameStatus?: boolean | null,
    textExperienceScreenHint?: boolean | null,
    textExperienceScreenImprintContent?: boolean | null,
    textExperienceScreenImprintHeading?: boolean | null,
    textExperienceScreenInstructionsContentOne?: boolean | null,
    textExperienceScreenInstructionsContentThree?: boolean | null,
    textExperienceScreenInstructionsContentTwo?: boolean | null,
    textExperienceScreenInstructionsHeading?: boolean | null,
    textExperienceScreenLogoStatus?: boolean | null,
    textFotoScreenHint?: boolean | null,
    textFotoScreenStatus?: boolean | null,
    textLoadingScreenHint?: boolean | null,
    textLoadingScreenStatus?: boolean | null,
    textStartScreenButton?: boolean | null,
    textStartScreenHeading?: boolean | null,
    textStartScreenStatus?: boolean | null,
    textStartScreenSubheading?: boolean | null,
    title: string,
  } | null,
};

export type GetProjectsQueryVariables = {
  id: string,
};

export type GetProjectsQuery = {
  getProjects?:  {
    __typename: "projects",
    colorEndScreenMain?: string | null,
    colorEndScreenSub?: string | null,
    colorExperienceScreenHint?: string | null,
    colorExperienceScreenMain?: string | null,
    colorExperienceScreenSub?: string | null,
    colorFontMain?: string | null,
    colorFontSub?: string | null,
    colorFotoScreenMain?: string | null,
    colorFotoScreenSub?: string | null,
    colorLoadingScreenMain?: string | null,
    colorLoadingScreenSub?: string | null,
    colorStartScreenMain?: string | null,
    colorStartScreenSub?: string | null,
    createdAt?: number | null,
    fontLoadingHeading?: string | null,
    fontLoadingMain?: string | null,
    id: string,
    imageEndScreenBackground?: string | null,
    imageEndScreenLogo?: string | null,
    imageExperienceScreenAvatar?: string | null,
    imageExperienceScreenLogo?: string | null,
    imageFotoScreenScreenBackground?: string | null,
    imageFotoScreenScreenLogo?: string | null,
    imageLoadingScreenBackground?: string | null,
    imageLoadingScreenLogo?: string | null,
    imageStartScreenBackground?: string | null,
    imageStartScreenLogo?: string | null,
    layoutActiveEndScreenStatus?: boolean | null,
    layoutActiveExperienceScreenFotoFrameStatus?: boolean | null,
    layoutActiveExperienceScreenLogoStatus?: boolean | null,
    layoutActiveFotoScreenStatus?: boolean | null,
    layoutActiveLoadingScreenStatus?: boolean | null,
    layoutActiveStartScreenStatus?: boolean | null,
    linkEndScreenButtonOne?: string | null,
    linkEndScreenButtonThree?: string | null,
    linkEndScreenButtonTwo?: string | null,
    paymentIntentId?: string | null,
    projectExperienceLayout?: string | null,
    projectLink?: string | null,
    projectName?: string | null,
    projectStatus?: string | null,
    projectType?: string | null,
    projectUrl?: string | null,
    templateId?: string | null,
    textEndScreenButtonOne?: string | null,
    textEndScreenButtonThree?: string | null,
    textEndScreenButtonTwo?: string | null,
    textEndScreenStatus?: string | null,
    textExperienceScreenFotoFrameStatus?: string | null,
    textExperienceScreenHint?: string | null,
    textExperienceScreenImprintContent?: string | null,
    textExperienceScreenImprintHeading?: string | null,
    textExperienceScreenInstructionsContentOne?: string | null,
    textExperienceScreenInstructionsContentThree?: string | null,
    textExperienceScreenInstructionsContentTwo?: string | null,
    textExperienceScreenInstructionsHeading?: string | null,
    textExperienceScreenLogoStatus?: string | null,
    textFotoScreenHint?: string | null,
    textFotoScreenStatus?: string | null,
    textLoadingScreenHint?: string | null,
    textLoadingScreenStatus?: string | null,
    textStartScreenButton?: string | null,
    textStartScreenHeading?: string | null,
    textStartScreenStatus?: string | null,
    textStartScreenSubheading?: string | null,
    updatedAt?: number | null,
  } | null,
};

export type GetUploadURLQueryVariables = {
  assetType: assetType,
  fileType: fileType,
  projectId: string,
};

export type GetUploadURLQuery = {
  getUploadURL?: string | null,
};

export type GetUserQuery = {
  getUser?:  {
    __typename: "User",
    available_templates?: string | null,
    email: string,
    id: string,
    name?: string | null,
  } | null,
};

export type ListProjectTemplatesQueryVariables = {
  filter?: TableProjectTemplateFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListProjectTemplatesQuery = {
  listProjectTemplates?:  {
    __typename: "projectTemplateConnection",
    items?:  Array< {
      __typename: "projectTemplate",
      colorEndScreenMain?: boolean | null,
      colorEndScreenSub?: boolean | null,
      colorExperienceScreenHint?: boolean | null,
      colorExperienceScreenMain?: boolean | null,
      colorExperienceScreenSub?: boolean | null,
      colorFontMain?: boolean | null,
      colorFontSub?: boolean | null,
      colorFotoScreenMain?: boolean | null,
      colorFotoScreenSub?: boolean | null,
      colorLoadingScreenMain?: boolean | null,
      colorLoadingScreenSub?: boolean | null,
      colorStartScreenMain?: boolean | null,
      colorStartScreenSub?: boolean | null,
      fontLoadingHeading?: boolean | null,
      fontLoadingMain?: boolean | null,
      id: string,
      imageEndScreenBackground?: boolean | null,
      imageEndScreenLogo?: boolean | null,
      imageExperienceScreenAvatar?: boolean | null,
      imageExperienceScreenLogo?: boolean | null,
      imageFotoScreenScreenBackground?: boolean | null,
      imageFotoScreenScreenLogo?: boolean | null,
      imageLoadingScreenBackground?: boolean | null,
      imageLoadingScreenLogo?: boolean | null,
      imageStartScreenBackground?: boolean | null,
      imageStartScreenLogo?: boolean | null,
      linkEndScreenButtonOne?: boolean | null,
      linkEndScreenButtonThree?: boolean | null,
      linkEndScreenButtonTwo?: boolean | null,
      picture: string,
      projectExperienceLayout?: boolean | null,
      projectLink?: boolean | null,
      projectName?: boolean | null,
      projectStatus?: boolean | null,
      projectType?: boolean | null,
      projectUrl?: boolean | null,
      textEndScreenButtonOne?: boolean | null,
      textEndScreenButtonThree?: boolean | null,
      textEndScreenButtonTwo?: boolean | null,
      textEndScreenStatus?: boolean | null,
      textExperienceScreenFotoFrameStatus?: boolean | null,
      textExperienceScreenHint?: boolean | null,
      textExperienceScreenImprintContent?: boolean | null,
      textExperienceScreenImprintHeading?: boolean | null,
      textExperienceScreenInstructionsContentOne?: boolean | null,
      textExperienceScreenInstructionsContentThree?: boolean | null,
      textExperienceScreenInstructionsContentTwo?: boolean | null,
      textExperienceScreenInstructionsHeading?: boolean | null,
      textExperienceScreenLogoStatus?: boolean | null,
      textFotoScreenHint?: boolean | null,
      textFotoScreenStatus?: boolean | null,
      textLoadingScreenHint?: boolean | null,
      textLoadingScreenStatus?: boolean | null,
      textStartScreenButton?: boolean | null,
      textStartScreenHeading?: boolean | null,
      textStartScreenStatus?: boolean | null,
      textStartScreenSubheading?: boolean | null,
      title: string,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type ListProjectsQueryVariables = {
  filter?: TableProjectsFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListProjectsQuery = {
  listProjects?:  {
    __typename: "projectsConnection",
    items?:  Array< {
      __typename: "projects",
      colorEndScreenMain?: string | null,
      colorEndScreenSub?: string | null,
      colorExperienceScreenHint?: string | null,
      colorExperienceScreenMain?: string | null,
      colorExperienceScreenSub?: string | null,
      colorFontMain?: string | null,
      colorFontSub?: string | null,
      colorFotoScreenMain?: string | null,
      colorFotoScreenSub?: string | null,
      colorLoadingScreenMain?: string | null,
      colorLoadingScreenSub?: string | null,
      colorStartScreenMain?: string | null,
      colorStartScreenSub?: string | null,
      createdAt?: number | null,
      fontLoadingHeading?: string | null,
      fontLoadingMain?: string | null,
      id: string,
      imageEndScreenBackground?: string | null,
      imageEndScreenLogo?: string | null,
      imageExperienceScreenAvatar?: string | null,
      imageExperienceScreenLogo?: string | null,
      imageFotoScreenScreenBackground?: string | null,
      imageFotoScreenScreenLogo?: string | null,
      imageLoadingScreenBackground?: string | null,
      imageLoadingScreenLogo?: string | null,
      imageStartScreenBackground?: string | null,
      imageStartScreenLogo?: string | null,
      layoutActiveEndScreenStatus?: boolean | null,
      layoutActiveExperienceScreenFotoFrameStatus?: boolean | null,
      layoutActiveExperienceScreenLogoStatus?: boolean | null,
      layoutActiveFotoScreenStatus?: boolean | null,
      layoutActiveLoadingScreenStatus?: boolean | null,
      layoutActiveStartScreenStatus?: boolean | null,
      linkEndScreenButtonOne?: string | null,
      linkEndScreenButtonThree?: string | null,
      linkEndScreenButtonTwo?: string | null,
      paymentIntentId?: string | null,
      projectExperienceLayout?: string | null,
      projectLink?: string | null,
      projectName?: string | null,
      projectStatus?: string | null,
      projectType?: string | null,
      projectUrl?: string | null,
      templateId?: string | null,
      textEndScreenButtonOne?: string | null,
      textEndScreenButtonThree?: string | null,
      textEndScreenButtonTwo?: string | null,
      textEndScreenStatus?: string | null,
      textExperienceScreenFotoFrameStatus?: string | null,
      textExperienceScreenHint?: string | null,
      textExperienceScreenImprintContent?: string | null,
      textExperienceScreenImprintHeading?: string | null,
      textExperienceScreenInstructionsContentOne?: string | null,
      textExperienceScreenInstructionsContentThree?: string | null,
      textExperienceScreenInstructionsContentTwo?: string | null,
      textExperienceScreenInstructionsHeading?: string | null,
      textExperienceScreenLogoStatus?: string | null,
      textFotoScreenHint?: string | null,
      textFotoScreenStatus?: string | null,
      textLoadingScreenHint?: string | null,
      textLoadingScreenStatus?: string | null,
      textStartScreenButton?: string | null,
      textStartScreenHeading?: string | null,
      textStartScreenStatus?: string | null,
      textStartScreenSubheading?: string | null,
      updatedAt?: number | null,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};
