/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const createProjectTemplate = /* GraphQL */ `
  mutation CreateProjectTemplate($input: CreateProjectTemplateInput!) {
    createProjectTemplate(input: $input) {
      colorEndScreenMain
      colorEndScreenSub
      colorExperienceScreenHint
      colorExperienceScreenMain
      colorExperienceScreenSub
      colorFontMain
      colorFontSub
      colorFotoScreenMain
      colorFotoScreenSub
      colorLoadingScreenMain
      colorLoadingScreenSub
      colorStartScreenMain
      colorStartScreenSub
      fontLoadingHeading
      fontLoadingMain
      id
      imageEndScreenBackground
      imageEndScreenLogo
      imageExperienceScreenAvatar
      imageExperienceScreenLogo
      imageFotoScreenScreenBackground
      imageFotoScreenScreenLogo
      imageLoadingScreenBackground
      imageLoadingScreenLogo
      imageStartScreenBackground
      imageStartScreenLogo
      linkEndScreenButtonOne
      linkEndScreenButtonThree
      linkEndScreenButtonTwo
      picture
      projectExperienceLayout
      projectLink
      projectName
      projectStatus
      projectType
      projectUrl
      textEndScreenButtonOne
      textEndScreenButtonThree
      textEndScreenButtonTwo
      textEndScreenStatus
      textExperienceScreenFotoFrameStatus
      textExperienceScreenHint
      textExperienceScreenImprintContent
      textExperienceScreenImprintHeading
      textExperienceScreenInstructionsContentOne
      textExperienceScreenInstructionsContentThree
      textExperienceScreenInstructionsContentTwo
      textExperienceScreenInstructionsHeading
      textExperienceScreenLogoStatus
      textFotoScreenHint
      textFotoScreenStatus
      textLoadingScreenHint
      textLoadingScreenStatus
      textStartScreenButton
      textStartScreenHeading
      textStartScreenStatus
      textStartScreenSubheading
      title
    }
  }
`;
export const createProjects = /* GraphQL */ `
  mutation CreateProjects($input: CreateProjectsInput!) {
    createProjects(input: $input) {
      colorEndScreenMain
      colorEndScreenSub
      colorExperienceScreenHint
      colorExperienceScreenMain
      colorExperienceScreenSub
      colorFontMain
      colorFontSub
      colorFotoScreenMain
      colorFotoScreenSub
      colorLoadingScreenMain
      colorLoadingScreenSub
      colorStartScreenMain
      colorStartScreenSub
      createdAt
      fontLoadingHeading
      fontLoadingMain
      id
      imageEndScreenBackground
      imageEndScreenLogo
      imageExperienceScreenAvatar
      imageExperienceScreenLogo
      imageFotoScreenScreenBackground
      imageFotoScreenScreenLogo
      imageLoadingScreenBackground
      imageLoadingScreenLogo
      imageStartScreenBackground
      imageStartScreenLogo
      layoutActiveEndScreenStatus
      layoutActiveExperienceScreenFotoFrameStatus
      layoutActiveExperienceScreenLogoStatus
      layoutActiveFotoScreenStatus
      layoutActiveLoadingScreenStatus
      layoutActiveStartScreenStatus
      linkEndScreenButtonOne
      linkEndScreenButtonThree
      linkEndScreenButtonTwo
      paymentIntentId
      projectExperienceLayout
      projectLink
      projectName
      projectStatus
      projectType
      projectUrl
      templateId
      textEndScreenButtonOne
      textEndScreenButtonThree
      textEndScreenButtonTwo
      textEndScreenStatus
      textExperienceScreenFotoFrameStatus
      textExperienceScreenHint
      textExperienceScreenImprintContent
      textExperienceScreenImprintHeading
      textExperienceScreenInstructionsContentOne
      textExperienceScreenInstructionsContentThree
      textExperienceScreenInstructionsContentTwo
      textExperienceScreenInstructionsHeading
      textExperienceScreenLogoStatus
      textFotoScreenHint
      textFotoScreenStatus
      textLoadingScreenHint
      textLoadingScreenStatus
      textStartScreenButton
      textStartScreenHeading
      textStartScreenStatus
      textStartScreenSubheading
      updatedAt
    }
  }
`;
export const createUser = /* GraphQL */ `
  mutation CreateUser($input: CreateUserInput!) {
    createUser(input: $input) {
      available_templates
      email
      id
      name
    }
  }
`;
export const deleteProjectTemplate = /* GraphQL */ `
  mutation DeleteProjectTemplate($input: DeleteProjectTemplateInput!) {
    deleteProjectTemplate(input: $input) {
      colorEndScreenMain
      colorEndScreenSub
      colorExperienceScreenHint
      colorExperienceScreenMain
      colorExperienceScreenSub
      colorFontMain
      colorFontSub
      colorFotoScreenMain
      colorFotoScreenSub
      colorLoadingScreenMain
      colorLoadingScreenSub
      colorStartScreenMain
      colorStartScreenSub
      fontLoadingHeading
      fontLoadingMain
      id
      imageEndScreenBackground
      imageEndScreenLogo
      imageExperienceScreenAvatar
      imageExperienceScreenLogo
      imageFotoScreenScreenBackground
      imageFotoScreenScreenLogo
      imageLoadingScreenBackground
      imageLoadingScreenLogo
      imageStartScreenBackground
      imageStartScreenLogo
      linkEndScreenButtonOne
      linkEndScreenButtonThree
      linkEndScreenButtonTwo
      picture
      projectExperienceLayout
      projectLink
      projectName
      projectStatus
      projectType
      projectUrl
      textEndScreenButtonOne
      textEndScreenButtonThree
      textEndScreenButtonTwo
      textEndScreenStatus
      textExperienceScreenFotoFrameStatus
      textExperienceScreenHint
      textExperienceScreenImprintContent
      textExperienceScreenImprintHeading
      textExperienceScreenInstructionsContentOne
      textExperienceScreenInstructionsContentThree
      textExperienceScreenInstructionsContentTwo
      textExperienceScreenInstructionsHeading
      textExperienceScreenLogoStatus
      textFotoScreenHint
      textFotoScreenStatus
      textLoadingScreenHint
      textLoadingScreenStatus
      textStartScreenButton
      textStartScreenHeading
      textStartScreenStatus
      textStartScreenSubheading
      title
    }
  }
`;
export const deleteProjects = /* GraphQL */ `
  mutation DeleteProjects($input: DeleteProjectsInput!) {
    deleteProjects(input: $input) {
      colorEndScreenMain
      colorEndScreenSub
      colorExperienceScreenHint
      colorExperienceScreenMain
      colorExperienceScreenSub
      colorFontMain
      colorFontSub
      colorFotoScreenMain
      colorFotoScreenSub
      colorLoadingScreenMain
      colorLoadingScreenSub
      colorStartScreenMain
      colorStartScreenSub
      createdAt
      fontLoadingHeading
      fontLoadingMain
      id
      imageEndScreenBackground
      imageEndScreenLogo
      imageExperienceScreenAvatar
      imageExperienceScreenLogo
      imageFotoScreenScreenBackground
      imageFotoScreenScreenLogo
      imageLoadingScreenBackground
      imageLoadingScreenLogo
      imageStartScreenBackground
      imageStartScreenLogo
      layoutActiveEndScreenStatus
      layoutActiveExperienceScreenFotoFrameStatus
      layoutActiveExperienceScreenLogoStatus
      layoutActiveFotoScreenStatus
      layoutActiveLoadingScreenStatus
      layoutActiveStartScreenStatus
      linkEndScreenButtonOne
      linkEndScreenButtonThree
      linkEndScreenButtonTwo
      paymentIntentId
      projectExperienceLayout
      projectLink
      projectName
      projectStatus
      projectType
      projectUrl
      templateId
      textEndScreenButtonOne
      textEndScreenButtonThree
      textEndScreenButtonTwo
      textEndScreenStatus
      textExperienceScreenFotoFrameStatus
      textExperienceScreenHint
      textExperienceScreenImprintContent
      textExperienceScreenImprintHeading
      textExperienceScreenInstructionsContentOne
      textExperienceScreenInstructionsContentThree
      textExperienceScreenInstructionsContentTwo
      textExperienceScreenInstructionsHeading
      textExperienceScreenLogoStatus
      textFotoScreenHint
      textFotoScreenStatus
      textLoadingScreenHint
      textLoadingScreenStatus
      textStartScreenButton
      textStartScreenHeading
      textStartScreenStatus
      textStartScreenSubheading
      updatedAt
    }
  }
`;
export const updateProjectTemplate = /* GraphQL */ `
  mutation UpdateProjectTemplate($input: UpdateProjectTemplateInput!) {
    updateProjectTemplate(input: $input) {
      colorEndScreenMain
      colorEndScreenSub
      colorExperienceScreenHint
      colorExperienceScreenMain
      colorExperienceScreenSub
      colorFontMain
      colorFontSub
      colorFotoScreenMain
      colorFotoScreenSub
      colorLoadingScreenMain
      colorLoadingScreenSub
      colorStartScreenMain
      colorStartScreenSub
      fontLoadingHeading
      fontLoadingMain
      id
      imageEndScreenBackground
      imageEndScreenLogo
      imageExperienceScreenAvatar
      imageExperienceScreenLogo
      imageFotoScreenScreenBackground
      imageFotoScreenScreenLogo
      imageLoadingScreenBackground
      imageLoadingScreenLogo
      imageStartScreenBackground
      imageStartScreenLogo
      linkEndScreenButtonOne
      linkEndScreenButtonThree
      linkEndScreenButtonTwo
      picture
      projectExperienceLayout
      projectLink
      projectName
      projectStatus
      projectType
      projectUrl
      textEndScreenButtonOne
      textEndScreenButtonThree
      textEndScreenButtonTwo
      textEndScreenStatus
      textExperienceScreenFotoFrameStatus
      textExperienceScreenHint
      textExperienceScreenImprintContent
      textExperienceScreenImprintHeading
      textExperienceScreenInstructionsContentOne
      textExperienceScreenInstructionsContentThree
      textExperienceScreenInstructionsContentTwo
      textExperienceScreenInstructionsHeading
      textExperienceScreenLogoStatus
      textFotoScreenHint
      textFotoScreenStatus
      textLoadingScreenHint
      textLoadingScreenStatus
      textStartScreenButton
      textStartScreenHeading
      textStartScreenStatus
      textStartScreenSubheading
      title
    }
  }
`;
export const updateProjects = /* GraphQL */ `
  mutation UpdateProjects($input: UpdateProjectsInput!) {
    updateProjects(input: $input) {
      colorEndScreenMain
      colorEndScreenSub
      colorExperienceScreenHint
      colorExperienceScreenMain
      colorExperienceScreenSub
      colorFontMain
      colorFontSub
      colorFotoScreenMain
      colorFotoScreenSub
      colorLoadingScreenMain
      colorLoadingScreenSub
      colorStartScreenMain
      colorStartScreenSub
      createdAt
      fontLoadingHeading
      fontLoadingMain
      id
      imageEndScreenBackground
      imageEndScreenLogo
      imageExperienceScreenAvatar
      imageExperienceScreenLogo
      imageFotoScreenScreenBackground
      imageFotoScreenScreenLogo
      imageLoadingScreenBackground
      imageLoadingScreenLogo
      imageStartScreenBackground
      imageStartScreenLogo
      layoutActiveEndScreenStatus
      layoutActiveExperienceScreenFotoFrameStatus
      layoutActiveExperienceScreenLogoStatus
      layoutActiveFotoScreenStatus
      layoutActiveLoadingScreenStatus
      layoutActiveStartScreenStatus
      linkEndScreenButtonOne
      linkEndScreenButtonThree
      linkEndScreenButtonTwo
      paymentIntentId
      projectExperienceLayout
      projectLink
      projectName
      projectStatus
      projectType
      projectUrl
      templateId
      textEndScreenButtonOne
      textEndScreenButtonThree
      textEndScreenButtonTwo
      textEndScreenStatus
      textExperienceScreenFotoFrameStatus
      textExperienceScreenHint
      textExperienceScreenImprintContent
      textExperienceScreenImprintHeading
      textExperienceScreenInstructionsContentOne
      textExperienceScreenInstructionsContentThree
      textExperienceScreenInstructionsContentTwo
      textExperienceScreenInstructionsHeading
      textExperienceScreenLogoStatus
      textFotoScreenHint
      textFotoScreenStatus
      textLoadingScreenHint
      textLoadingScreenStatus
      textStartScreenButton
      textStartScreenHeading
      textStartScreenStatus
      textStartScreenSubheading
      updatedAt
    }
  }
`;
export const updateUser = /* GraphQL */ `
  mutation UpdateUser($input: UpdateUserInput!) {
    updateUser(input: $input) {
      available_templates
      email
      id
      name
    }
  }
`;
